### ISSUE TITLE
macpack not working properly

### ISSUE THREAD

**Issue by joeblew99** [murlokswarm/examples#1]
i tried to macpack the hello example.

i did not get a runable main.app.

also i am confused because the readme says that macpack will create a resources folder.
but the hello example has one already.

could you give me more detail instructions.

**Comment by maxence-charriere** [comment]
Hi @joeblew99 
macpack will create *[name of the repo].app*

The *./resources* directory is created only if it does not already exists (which is the case in the example).
the *resources* dir is where the resources required to make your app run should be (css, images, etc...).
When macpack runs, it creates the .app and copy the content of *./resources* in *./[your package].app/Contents/Resources*

**Comment by maxence-charriere** [comment]
Also, macpack creates ```./mac.json``` where you can customize things like the name of the app.

**Comment by joeblew99** [comment]
Ok, but for the hello example i cant get a runable .app out of it.
its creates the file, but it wont run

here is what i did exactly:

````

x-MacBook-Pro:hello apple$ macpack ./hello
x-MacBook-Pro:hello apple$ tree
.
├── hello
├── hello.app
│   └── Contents
│       ├── Info.plist
│       ├── MacOS
│       │   └── hello
│       └── Resources
│           ├── bin
│           ├── hello -> ./bin/hello
│           └── hello.exe
├── hello.go
├── mac.json
├── main.go
├── menu.go
└── resources
    ├── bg1.jpg
    ├── css
    │   ├── hello.css
    │   └── hello.css.map
    ├── js
    ├── logo.png
    ├── scss
    │   └── hello.scss
    └── star.png

9 directories, 15 files


x-MacBook-Pro:hello apple$ open hello.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/apple/workspace/go/src/github.com/murlokswarm/examples/mac/hello/hello.app.

````

**Comment by maxence-charriere** [comment]
Resource dir in .app looks not good, 
```./[your package].app/Contents/Resources``` should be the exact replica of ```./resources```

Try delete the whole hello app and run ```macpack``` again.

**Comment by maxence-charriere** [comment]
Updated previous command,
Have to launch ```macpack build```

**Comment by joeblew99** [comment]
tried that, but still not working for me.

i dont want to push it.

If you get time later, miht be a good idea to work up macpack working with this sample, with some basic readme example.

Will leave this open

**Comment by maxence-charriere** [comment]
I think the problem is that you are using macpack outside of your repo.
you have to go in the folder where the sources are.

Currently you are using it like you would use ``` go build ./hello```.
You should go in the hello folder and use ``` macpack build``` within. 

macpack launches ```go build``` under the hood and looking for the ```resources``` dir.

**Comment by maxence-charriere** [comment]
Beside, I'm so sorry, I just realized I didn't merge the last modifications I did on macpack.
Just go inside the hello dir (where there is the go files) and launch ```macpack build```

**Comment by joeblew99** [comment]
hehe.

no probs. will give it a whirl..

**Comment by joeblew99** [comment]
any chance you can make an example that is designed to show off what macpack does ?
there is allot of functionality in there i can see, and its hard to get to the bottom of it.
I am getting weird errors and its hard to see whats really going on.

Maybe a project thats simple and shows off the capabilities etc ?

**Comment by maxence-charriere** [comment]
the flags are only options. They can be set in command line or in mac.config.
if you have a mac.config generated from the previous version, get rid of it.
This could cause some problems (my bad, i really though this was live when i started communicating about the package).

I don't see how to do more simple than go to the the hello dir and run ```macpack run```

if it error, it will give you the message right before the usage description.
Maybe you can copy past what it does and i can help you fix what is wrong.

**Comment by joeblew99** [comment]
ok i see your point. It seems it more about usage patterns.

Maybe then write up what you wrote above into a markdown doc so others can see the way to use it ?
Will close this.
