### ISSUE TITLE
Example Hello doesn't work

### ISSUE THREAD

**Issue by raguay** [murlokswarm/examples#2]
I'm trying to figure out this package to update the content, but even this example doesn't work. I type my name and press enter or tab and the "Hello, World" is still there. Same with my program I'm trying to create. To me, the code is correct from the documentations. Therefore, I'm not sure what is wrong.

BTW: I'm using macOS Siera 10.12.4 Beta (16E144f). Since it's using the system built in HTML browser, I'm wondering if this library isn't working with this version of the OS?

**Comment by maxence-charriere** [comment]
Hello @raguay,
This could be because some pr related to event has beed merged.
is your events are still prefixed with ```'_'```?
e.g: 
```_onclick="OnClick"```

If yes, this is not required
```onclick="OnClick"```
is the correct way.

be sur to upgrade all the packages
```go get -u github.com/murlokswarm/mac```

Let me know if it resolved your issue.

**Comment by raguay** [comment]
The update and checking all the onclick has fixed my issues. Thanks.

**Comment by maxence-charriere** [comment]
👍 glad to hear it
